image: Visual Studio 2015

configuration:
  - Release

platform:
  - Win32
  - x64

before_build:
  - cmd: ver
  - cmd: git -C .. clone -q https://github.com/MediaArea/zlib.git
  - cmd: git -C .. clone -q https://github.com/MediaArea/ZenLib.git
  - cmd: git -C .. clone -q https://github.com/MediaArea/MediaInfoLib.git
  - cmd: git -C .. clone -q https://github.com/MediaArea/wxWidgets.git
  - ps: >-
      $Env:PATH += ";C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin";
      $Env:PATH += ";C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64";
      If ($Env:PLATFORM -Eq "Win32") {
        Push-Location ..\zlib\contrib\masmx86
        ml /nologo /coff /safeseh /Zi /c /Flmatch686.lst match686.asm
        ml /nologo /coff /safeseh /Zi /c /Flinffas32.lst inffas32.asm
        Pop-Location
      } Else {
        Push-Location ..\zlib\contrib\masmx64
        ml64 /nologo /Zi /c /Flinffasx64 inffasx64.asm
        ml64 /nologo /Zi /c /Flgvmat64 gvmat64.asm
        Pop-Location
      }

environment:
  matrix:
  - solution_name: MediaInfo_Qt
    solution_filename: MediaInfo_Qt.vcxproj
  - solution_name: GUI
    solution_filename: MediaInfo_GUI.vcxproj
  - solution_name: CLI
    solution_filename: MediaInfo.vcxproj

build_script:
  - cmd: if exist "..\Qt" rd "..\Qt"
  - cmd: if %solution_name%_%PLATFORM%==MediaInfo_Qt_Win32 MKLINK /J "..\Qt" "C:\Qt\5.6.3\msvc2015"
  - cmd: if %solution_name%_%PLATFORM%==MediaInfo_Qt_x64 MKLINK /J "..\Qt" "C:\Qt\5.6.3\msvc2015_64"
  - cmd: if %solution_name%==MediaInfo_Qt call Project\MSVC2015\%solution_name%\qt_update.bat
  - msbuild Project\MSVC2015\%solution_name%\%solution_filename%

artifacts:
  - path: Project\MSVC2015\%solution_name%\%PLATFORM%
    name: MediaInfo_MSVC2015_%solution_name%_%PLATFORM%
    type: zip
